version: "3.9"

services:
  db:
    build: ./db
    image: mysql:8.0.31
    container_name: mysql-dbap
    restart : always
    volumes:
      - db:/var/lib/mysql
      - db:/init-database.sql/docker-entrypoint-initdb.d/init-database.sql
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      MYSQL_DATABASE: ${DATABASE_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_USER : ${DATABASE_USERNAME}

  backend:
    image: node:alpine
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    working_dir: /usr/src/app

    container_name: backend
    links:
      - db:${DATABASE_HOST}
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    expose:
      - "${PORT}"
    command: 'node dist/main.js'
    restart: unless-stopped
    env_file: .env
volumes:
  db:
    driver: local